---

# == Notes ==

# - GitLab automatically passes artifacts from previous stages by default
# - This project requires runners with specific tags to execute specific jobs
# - This project includes variables specific to using 'Docker In Docker'
# - This project uses additional services ran alongside the job images
# - Set required secret variables at: https://gitlab.data.bas.ac.uk/web-apps/arctic-office-projects-manager/settings/ci_cd

# = Secret variables
# - Variables are grouped by section in KEY: "value" format (e.g. FOO: "bar")
#   Sensitive values are represented by "[Sensitive]"
#
# - Heroku
# > HEROKU_API_KEY: "[Sensitive]"
#
# - Sentry
# > SENTRY_AUTH_TOKEN: "[Sensetive]"
# > SENTRY_DSN: "[Sensetive]"
#
# - Snyk
# > SNYK_TOKEN: "[Sensitive]"

# == Global settings ==

stages:
  - test
  - lint
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  GITLAB_REGISTRY: docker-registry.data.bas.ac.uk
  APP_NAME: arctic-office-projects-manager
  HEROKU_APP_STAGE_NAME: bas-arctic-projects-app-stage
  HEROKU_APP_PROD_NAME: bas-arctic-projects-app-prod
  SENTRY_ORG: antarctica
  SENTRY_PROJECT: arctic-office-projects-manager
  SNYK_ORG: antarctica
  SNYK_PROJECT: arctic-office-projects-manager

image:
  name: docker-registry.data.bas.ac.uk/web-apps/arctic-office-projects-manager:latest
  entrypoint: [""]

# == Jobs ==

test-app:
  stage: test
  variables:
    FLASK_ENV: testing
  script:
    - "flask test"

dependencies-app:
  stage: lint
  image:
    name: antarctica/snyk-cli:python-3
    entrypoint: [""]
  script:
   - "apt-get update && apt-get install -y git --no-install-recommends"
   - "pip install -r requirements.txt"
   - "snyk test"
   - "snyk monitor --project-name=$SNYK_PROJECT --org=$SNYK_ORG"
  only:
    - master

pep8-app:
  stage: lint
  script:
    - "flake8 . --ignore=E501"

bandit-app:
  stage: lint
  script:
    - "bandit -r ."

build-heroku-stage:
  stage: build
  tags:
    - dnd
  services:
    - docker:dind
  image:
    name: docker:stable-dind
    entrypoint: [""]
  script:
    - "docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $GITLAB_REGISTRY"
    - "docker login -u _ -p $HEROKU_API_KEY registry.heroku.com"
    - "docker build -t registry.heroku.com/$HEROKU_APP_STAGE_NAME/web -f Dockerfile.heroku --build-arg APP_RELEASE=$CI_COMMIT_SHA --build-arg APP_ENV=staging ."
    - "docker build -t registry.heroku.com/$HEROKU_APP_STAGE_NAME/release -f Dockerfile.heroku-release ."
    - "docker push registry.heroku.com/$HEROKU_APP_STAGE_NAME/web"
    - "docker push registry.heroku.com/$HEROKU_APP_STAGE_NAME/release"
  only:
    - master

build-heroku-prod:
  stage: build
  tags:
    - dnd
  services:
    - docker:dind
  image:
    name: docker:stable-dind
    entrypoint: [""]
  script:
    - "docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $GITLAB_REGISTRY"
    - "docker login -u _ -p $HEROKU_API_KEY registry.heroku.com"
    - "docker build -t registry.heroku.com/$HEROKU_APP_PROD_NAME/web -f Dockerfile.heroku --build-arg APP_RELEASE=$CI_COMMIT_SHA --build-arg APP_ENV=production ."
    - "docker build -t registry.heroku.com/$HEROKU_APP_PROD_NAME/release -f Dockerfile.heroku-release ."
    - "docker push registry.heroku.com/$HEROKU_APP_PROD_NAME/web"
    - "docker push registry.heroku.com/$HEROKU_APP_PROD_NAME/release"
  only:
    - tags

deploy-heroku-stage:
  stage: deploy
  image:
    name: wingrunr21/alpine-heroku-cli
    entrypoint: [""]
  script:
    - "heroku container:release web release --app $HEROKU_APP_STAGE_NAME"
  only:
    - master
  environment:
    name: Staging
    url: https://arctic-office-projects-testing.web.bas.ac.uk

deploy-heroku-prod:
  stage: deploy
  image:
    name: wingrunr21/alpine-heroku-cli
    entrypoint: [""]
  script:
    - "heroku container:release web release --app $HEROKU_APP_PROD_NAME"
  only:
    - tags
  environment:
    name: Production
    url: https://arctic-office-projects.web.bas.ac.uk

sentry-stage:
  stage: deploy
  image:
    name: getsentry/sentry-cli
    entrypoint: [""]
  script:
    - "sentry-cli releases new --finalize $CI_COMMIT_SHA"
    - "sentry-cli releases deploys $CI_COMMIT_SHA new -e staging"
  only:
    - master

sentry-prod:
  stage: deploy
  image:
    name: getsentry/sentry-cli
    entrypoint: [""]
  script:
    - "sentry-cli releases new --finalize $CI_COMMIT_SHA"
    - "sentry-cli releases deploys $CI_COMMIT_SHA new -e production"
  only:
    - tags
